---
- name: Create private IP address to the VM instance
  gcp_compute_address:
    name: "{{ zone }}-ip"
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    service_account_file: "{{ gcp_cred_file }}"
    auth_kind: "{{ gcp_auth_kind }}"
  register: gce_ip

- name: Create a Google Cloud Platform virtual machine instance
  gcp_compute_instance:
    name: instance-1
    project: "{{ gcp_project }}"
    zone: "{{ zone }}"
    machine_type: "{{ machine_type }}"
    network_interfaces:
      - access_configs:
        - name: External NAT
          nat_ip: "{{ gce_ip }}"
          type: ONE_TO_ONE_NAT
    scopes:
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring.write
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
      - https://www.googleapis.com/auth/trace.append
      - https://www.googleapis.com/auth/compute
      - https://www.googleapis.com/auth/cloud-platform
    disks:
      - initialize_params:
          source_image: "{{ boot_disk_image }}"
          disk_size_gb: "{{ boot_disk_size_gb }}"
          disk_type: "{{ boot_disk_type }}"
        auto_delete: true
        boot: true
        device_name: my-instance
    shielded_instance_config:
      enable_secure_boot: false
      enable_vtpm: true
      enable_integrity_monitoring: true
    labels:
      ec-src: vm_add-gcloud
    auth_kind: "{{ gcp_auth_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
